### ISSUE TITLE
Replays by ID on lobby rather than using the website

### ISSUE THREAD

**Issue by Kalvirox** [FAForever/lobby#177] opened 2015-02-19 13:41 UTC
Edit the replay finder so that we can search replays by ID directly from the FAF lobby rather than using 
http://content.faforever.com/faf/vault/replay_vault/replay.php?id=ENTERIDHERE

**Comment by anihilnine** [comment] 2015-02-19 13:52
this would be nice. and search by second players name

**Comment by Sheeo** [comment] 2015-02-19 16:26
Duplicate of #146

**Closed by Sheeo** 2015-02-19 16:26 UTC
