### ISSUE TITLE
Validate closed issues

### ISSUE THREAD

**Issue by Sheeo** [FAForever/lobby#165] opened 2015-01-20 19:39 UTC
We need to verify whether these issues should have been closed or not:

[FAForever/lobby] Issue closed: #138 Profile for FAF 
[FAForever/lobby] Issue closed: #147 Bug friend disappears 
[FAForever/lobby] Issue closed: #148 Mouse problem 
[FAForever/lobby] Issue closed: #152 Offline message 
[FAForever/lobby] Issue closed: #155 Remove the dark-blue color 
[FAForever/fa] Issue closed: FAForever/fa#351 Map preview bug 
[FAForever/fa] Issue closed: FAForever/fa#346 Screenshot hotkeys 
[FAForever/fa] Issue closed: FAForever/fa#342 Horn button 
[FAForever/fa] Issue closed: FAForever/fa#341 Faction Selector 
[FAForever/fa] Issue closed: FAForever/fa#333 Pause button ingame 
[FAForever/fa] Issue closed: FAForever/fa#330 Error on swapping players 
[FAForever/fa] Issue closed: FAForever/fa#326 Player in lobby slot and listed as observer simultaneously 
[FAForever/fa] Issue closed: FAForever/fa#324 Lobby preset bug 
[FAForever/fa] Issue closed: FAForever/fa#321 Warning SafeQuit 
[FAForever/fa] Issue closed: FAForever/fa#276 System message broken 
[FAForever/fa] Issue closed: FAForever/fa#171 Enhancements Restrictions and SACU Preset problem 
[FAForever/fa] Issue closed: FAForever/fa#322 Kick player and Close the Host bug

**Comment by ChrisKitching** [comment] 2015-01-20 23:16
"I'll scweam and scweam and scweam".

Auditing and re-filing...

#138 seems potentially interesting: Remember how some of the problems we're currently considering (such as those vanishing options) occur only on a fresh profile?
Filed #166

#147 "Sometimes I lose friends without any reason"
#148 -> #167
#152 -> #168
#155 does indeed seem to be a duplicate of #64.

FAForever/fa#351 -> FAForever/fa#384
FAForever/fa#333 -> FAForever/fa#385
FAForever/fa#330 -> FAForever/fa#386
FAForever/fa#326 -> FAForever/fa#387
FAForever/fa#341 This seems only to occur for blank profiles, so it can just fall under the umbrella of #138.
FAForever/fa#346, FAForever/fa#342 These don't seem pointful.
FAForever/fa#324 Didn't the stuff that IceDreamer fished out of the tangled Xinnony PR include a fix for this? I can't reproduce it on current develop, anyway.
FAForever/fa#321 Not a bug: should probably be closed. The logic needed to avoid the logspam is sort of irritating, and all messages so produced are clearly labelled with "Don't panic", and will only ever occur exactly 1s before program termination.
FAForever/fa#276 If you recall, @Sheeo, we duct-taped this with the hotfix. A discussion needs to occur about this "filter out system messages" feature and what exactly we want it to do. Filed FAForever/fa#388
FAForever/fa#171 Incomprehensible.
FAForever/fa#322 -> FAForever/fa#389

**Closed** 2015-01-23 00:25 UTC
